### ISSUE TITLE
[3.4節]変数名の誤字（？）

### ISSUE THREAD

**Issue by je6bmq** [k3kaimu/simpleldpc#1]
https://github.com/k3kaimu/simpleldpc/blob/b994713c82ff35a81f86a2010ebc3578147b3aca/document/LDPCintro/LDPCintro.tex#L209

この節の文脈からして  $\mathrm{P}^y$ ではなく，$\mathrm{R}^y$ の誤りではないですか？

**Comment by k3komatsu** [comment]
ありがとうございます，たしかに誤ってますね．修正します
